version: '2'
services:
    topten:
        container_name: topten
        image: node:boron
        command: bash -c "yarn install && npm start"
        working_dir: /usr/src/app
        volumes:
            - ./topten:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - PORT=3001

    gateway:
        container_name: gateway
        image: node:boron
        command: bash -c "yarn install && npm start"
        working_dir: /usr/src/app
        volumes:
            - ./gateway:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            - "8000:8000"
        environment:
            - PORT=8000
            - TOPTEN_HOST=topten
            - TOPTEN_PORT=3001
        depends_on:
            - topten


